---
- name: Key Rotation Playbook
  hosts: hsr_ring
  become: yes
  gather_facts: no
  serial: 1  # Execute one host at a time

  tasks:
    - name: Run send_new_keys.sh on the current host
      shell: "/home/gutasi/Documents/thesis/send_new_keys.sh 2>/dev/null"
      register: send_keys_output
      ignore_errors: yes

    - name: Debug output of send_new_keys
      debug:
        msg: "Host {{ inventory_hostname }} returned: {{ send_keys_output.stdout }}"
      #when: send_keys_output.stdout is defined and send_keys_output.stdout != ""

    - name: Set fact for the sender host
      set_fact:
        sender_host: "{{ inventory_hostname }}"
      when: send_keys_output.stdout is defined and send_keys_output.stdout != ""

    - name: Wait for all hosts to complete the send_new_keys task
      pause:
        seconds: 1

    - name: Run enable_sa.py on all hosts
      shell: "python3 /home/gutasi/Documents/thesis/enable_sa.py"
      ignore_errors: yes

    - name: Run prep_new_key.py on all hosts except the one that sent new keys
      shell: "python3 /home/gutasi/Documents/thesis/prep_new_key.py"
      ignore_errors: yes
      when: inventory_hostname != hostvars[sender_host].ansible_hostname
