- name: My first play
  hosts: hsr_ring
  vars_files:
    - vars.yaml
  gather_facts: false
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Print message
      ansible.builtin.debug:
        msg: "{{ my_variable  }}"
